import Head from 'next/head'
import Image from 'next/image'

import Form from '../components/Form'
import StudentList from '../components/StudentList'


export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="row align-items-start b-2">
          <Form />
          <StudentList />
        </div>
      </main>
      
    </div>
  )
}




